# 퓨온 2주차 멘토링 
- **한림대학교 빅데이터전공 20155342 지현규**

## R 기초 자료형

### 1) 기본자료형 (6가지)

- 문자형(character) :문자, 문자열
- 수치형(numeric) 
- 정수(integer) - 1L, 20L (L부호는 정수형으로 데이터를 저장하도록 R에게 일러준다)
- 실수(double) - 1, 20, 3.14, 2.1
- 복소수형(complex) : 실수 + 허수
- 논리형 (logical) : TRUE(T, 1), FALSE(F, 0)

### 2) 특수한 형태의 값

- NULL : 데이터의 값이 존재하지 않는다는 의미이다.
- NA : missing value, 결측값, 손실된값으로 값이 없음을 의미한다. 하나의 요소의 의미
- NaN(not a number) :수학적으로 정의되지 않은 값
- Inf, -Inf :무한대
- 자료형 확인 함수 : mode(), typeof() : 자료형 확인

##### 아래 내용을 입력후 Ctrl + Enter로 한줄씩 실행, 결과는 Console에서 확인

In [9]:
mode(1)

[1] "numeric"

In [10]:
mode(1L)

[1] "numeric"

In [11]:
mode(3.14)

[1] "numeric"

In [12]:
mode('홍길동')

[1] "character"

In [13]:
mode(3+4i)

[1] "complex"

In [14]:
mode(TRUE)

[1] "logical"

In [15]:
typeof(2.3)

[1] "double"

In [16]:
typeof(1L)

[1] "integer"

In [17]:
typeof(1)

[1] "double"

In [18]:
typeof(TRUE)

[1] "logical"

In [19]:
typeof('홍길동')

[1] "character"

In [20]:
typeof('3+4i')

[1] "character"

## 자료구조

### 1. 원자배열(atomic vector) = 벡터
- 벡터가 R에서 가장 일반적이고 기본이 되는 자료구조
- 벡터는 Charater, Logical, integer, numeric을 요소로 갖는 집합(collection)
- 한 벡터 내의 타입은 항상 같아야 함
- 벡터를 만드는 가장 간단한 방법은 c()함수
- 숫자형 데이터인 경우 **시작값:끝값** 형태와 **seq(from,to,by)**로 사용 가능
- seq_along() : **주어진 인자데이터 길이** 만큼 1,2,3... 길이까지 벡터로 변환된다.
- seq_leng() : **주어진 인자값**까지 1,2,3,,, 인자값까지 벡터로 변환한다.
- rep() : 일정한 패턴들을 반복적으로 사용하여 벡터를 만든다.

In [23]:
x<-c(1,2,3,4,5,6,7,8,9,10)
x

[1]  1  2  3  4  5  6  7  8  9 10

In [24]:
c('1','2','3','4',c('1','2','3'))

[1] "1" "2" "3" "4" "1" "2" "3"

In [27]:
x<-1:10
x

[1]  1  2  3  4  5  6  7  8  9 10

In [29]:
x<-2:9
x

[1] 2 3 4 5 6 7 8 9

In [31]:
seq(1,10,2)

[1] 1 3 5 7 9

In [33]:
seq(5,8)

[1] 5 6 7 8

In [35]:
seq_along(c('a','b','c','d')) # 1,2,3,4

[1] 1 2 3 4

In [36]:
seq_len(5) # 1,2,3,4,5

[1] 1 2 3 4 5

In [38]:
rep(1:3,5) # 1:3 형식을 5번 반복하여 백터생성

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [39]:
rep(1:5, each=3) #1~5까지 각각의 수를 3번씩 반복하여 벡터를 생성

[1] 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5

##### names() 함수로 이름을 부여할 수 있다.

In [46]:
x <- c(1,3,5,7)
names(x) <- c('noh,','kim','park','jun')
x

noh,  kim park  jun 
   1    3    5    7

#### 백터의 요소접근
- 벡터의 데이터는 [인덱스]로 요소를 가져온다. 인덱스는 1부터 시작
- 벡터의 **여러개의 데이터를 가져오기 위해 벡터의 형식**을 사용

In [53]:
x <- c('a','b','c','d')
x[1]
x[4]

[1] "a"

[1] "d"

In [60]:
x[c(1,3)] # 1,3 인덱스의 값이 추출

[1] "a" "c"

In [61]:
x[c(1:3)] # 1~3 인덱스의 값이 추출

[1] "a" "b" "c"

##### [-] 음수의 인덱스를 사용하여 특정한 요소를 제거하고 가져온다

In [76]:
x[-3] # 'c' 만 빼고 x를 가져온다.

[1] "a" "b" "d"

##### 백터의 길이를 알아내는 함수로는 length(), NROW()이다.

In [66]:
NROW(x) # NROW()는 행렬에서 사용하는 함수이므로 N행 1열로 취급한다.
length(x)

[1] 4

[1] 4

##### %in%을 사용하여 벡터에 포함된 값을 확인할 수 있다.

In [72]:
'c'%in%c('a','b','c','d')
'e'%in%x

[1] TRUE

[1] FALSE

### 2. 배열(Array) 
- 벡터와 행렬의 값을 나타낸다.
- 한가지 형태의 자료형의 값으로 구성되어 있다.
- 문자와 숫자를 혼합에서 사용하면 에러발생
- **1차원 배열은 벡터, 2차원 배열은 행렬이라 한다.**
- 3차원 이상의 차원 구조도 가능하다
- dim은 dimension의 약자로 **차원**이란 뜻이다.
- length로 배열의 크기를 알 수 있다.
- 배열의 생성은 **dim(), array()**를 사용한다.

In [79]:
array(1:20,dim=c(4,5))

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [84]:
array(1:20,dim=c(4,4,3))

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16

, , 2

     [,1] [,2] [,3] [,4]
[1,]   17    1    5    9
[2,]   18    2    6   10
[3,]   19    3    7   11
[4,]   20    4    8   12

, , 3

     [,1] [,2] [,3] [,4]
[1,]   13   17    1    5
[2,]   14   18    2    6
[3,]   15   19    3    7
[4,]   16   20    4    8

In [85]:
array(1:6)

[1] 1 2 3 4 5 6

In [87]:
array(1:6,c(2,3))

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [94]:
arr<-c(1:24)# 1~24 의 자료생성
dim(arr) <- c(3,4,2) # dim()함수를 이용하여 3행 4열의 행렬 2개생성
arr

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

##### 같은 크기의 배열같의 사칙연산 및 같은 위치의 원소간의 연산을 수행할 수 있다.
##### 숫자와 배열 또는 배열과 숫자간의 산술 연산도 가능하다.

In [118]:
arr1 <- array(1:4, dim=c(2,2))
arr2 <- array(4:1, dim=c(2,2))
arr1
arr2
arr1 + arr2
arr1 * arr2 # 두 배열 원소들의 곱의 합
arr1 %*% arr2 # 행렬곱

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 4    2   
[2,] 3    1

[,1] [,2]
[1,] 5    5   
[2,] 5    5

[,1] [,2]
[1,] 4    6   
[2,] 6    4

[,1] [,2]
[1,] 13   5   
[2,] 20   8

### 3. 행렬
- 표형식의 데이터를 분석함수를통해 사용하기 위해 행렬화 해서 사용한다.
- 행렬은 merticx()함수를 이용하여 생성한다.
- 벡터에 차원을 추가하여서도 행렬을 만들수 있다.

In [125]:
a<-1:9
a

[1] 1 2 3 4 5 6 7 8 9

In [128]:
dim(a) <- c(3,3)
a

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [130]:
mat1 <- matrix(1:10, nrow=2) # 1~10개의 행으로 만든다.
mat1

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [134]:
mat2 <- matrix(1:10, ncol=2) # 1~10 2개의 열로 만든다
mat2

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

##### 행과 열 이름주기

In [142]:
names <- list(c("1행","2행"), c("1열", "2열", "3열"))
matrix(1:6, nrow=2, byrow=TRUE, dimnames=names)
# 행을 우선적으로 만든다 byrow = True

1열 2열 3열
1행 1   2   3  
2행 4   5   6

## 4. 리스트(list)
- 여러데이터 타입을 가지는 데이터 구조이다.
- 리스트요소에 이름을 부여할 수 있다.
- list()함수로 리스트를 생성한다.

In [145]:
x <- list("홍길동", "2016001", "20", c("융합소프트웨어", "빅데이터 관리"))
x

[[1]]
[1] "홍길동"

[[2]]
[1] "2016001"

[[3]]
[1] "20"

[[4]]
[1] "융합소프트웨어" "빅데이터 관리"

In [149]:
y <- list("성명"="홍길동", "학번"="2016001", "나이"=20, "수강과목"=c("융합소프트웨어",
"빅데이터 관리"))
y

$성명
[1] "홍길동"

$학번
[1] "2016001"

$나이
[1] 20

$수강과목
[1] "융합소프트웨어" "빅데이터 관리"

In [147]:
# 위 결과와 동일
x<-list(성명="홍길동", 학번="2016001",나이=20,수강과목=c("융합소프트웨어", "빅데이터 관리"))
x

$성명
[1] "홍길동"

$학번
[1] "2016001"

$나이
[1] 20

$수강과목
[1] "융합소프트웨어" "빅데이터 관리"

##### 객체 값의 출력

In [156]:
y["성명"]

$성명
[1] "홍길동"

In [157]:
y[["성명"]]

[1] "홍길동"

In [158]:
y$성명

[1] "홍길동"

## 5. 데이터프레임(data frame)
- 동일한 속성들을 가지는 여러개체들로 구성되며, 각 속성들의 데이터 유형은 서로 다를 수 있다.
- 데이터프레임은 data.frame()함수로 생성한다.

##### 두 명의 고객정보에 대한 데이터 프레임 만들기

In [168]:
x <- data.frame(성명=c("홍길동", "손오공"), 나이=c(20,30), 주소=c("서울","부산"))
x

# 동일한 결과
x <- data.frame("성명"=c("홍길동", "손오공"), "나이"=c(20, 30), "주소"=c("서울", "부산"))
x

성명   나이 주소
1 홍길동 20   서울
2 손오공 30   부산

성명   나이 주소
1 홍길동 20   서울
2 손오공 30   부산

##### 열과 행 단위 추가

In [183]:
# x<-cbind(x,학과=c("e-비즈","경영"))
# x

x<-rbind(x,data.frame(성명="장발장",나이=40,주소="파리",학과="행정"))
x

성명   나이 주소 학과  
1 홍길동 20   서울 e-비즈
2 손오공 30   부산 경영  
3 장발장 40   파리 행정  
4 장발장 40   파리 행정  
5 장발장 40   파리 행정

##### 요소 값 보기

In [186]:
x[3,2]

[1] 40

In [187]:
x[3,]

성명   나이 주소 학과
3 장발장 40   파리 행정

In [188]:
x[,2]

[1] 20 30 40 40 40

In [189]:
x[-2,]

성명   나이 주소 학과  
1 홍길동 20   서울 e-비즈
3 장발장 40   파리 행정  
4 장발장 40   파리 행정  
5 장발장 40   파리 행정

In [190]:
x["성명"]

성명  
1 홍길동
2 손오공
3 장발장
4 장발장
5 장발장

In [191]:
x$성명

[1] 홍길동 손오공 장발장 장발장 장발장
Levels: 손오공 홍길동 장발장

In [198]:
x[["성명"]]

[1] 홍길동 손오공 장발장 장발장 장발장
Levels: 손오공 홍길동 장발장

In [203]:
x[[1]]

[1] 홍길동 손오공 장발장 장발장 장발장
Levels: 손오공 홍길동 장발장

In [204]:
x[[1]][2]

[1] 손오공
Levels: 손오공 홍길동 장발장

In [208]:
x[1,2] <- 21
x

성명   나이 주소 학과  
1 홍길동 21   서울 e-비즈
2 손오공 30   부산 경영  
3 장발장 40   파리 행정  
4 장발장 40   파리 행정  
5 장발장 40   파리 행정

In [210]:
x[1,"나이"]<-22
x

성명   나이 주소 학과  
1 홍길동 22   서울 e-비즈
2 손오공 30   부산 경영  
3 장발장 40   파리 행정  
4 장발장 40   파리 행정  
5 장발장 40   파리 행정

### 3. 요인(factors)
- R에서 factor(요인)을 범주형 변수(categorical variable)로 취급한다.

##### - 아래 gender의 값은 f이고 수준은 m,f 2개이다. [m,f는 범주형 변수]

In [218]:
gender<-factor("f", c("m","f"))
gender

[1] f
Levels: m f

##### 범주의 값을 구한다.
##### levels() 함수로 범주의 값을 변경할 수 있다.

In [221]:
levels(gender)[1]
levels(gender)[2]

[1] "m"

[1] "f"

In [222]:
gender

[1] f
Levels: m f

In [224]:
levels(gender)<-c("male","female")
gender

[1] female
Levels: male female

##### ordered() 함수를 이용하여 명목형 변수의 level에 순서를 적용할 수 있다.
##### factor()에서는 ordered =True 라고 지정한다.

In [229]:
ordered(c("a","b","c","d"))
factor(c('a','b','c','d'), ordered=TRUE) # 위와 같은 순서가 있는 factor

[1] a b c d
Levels: a < b < c < d

[1] a b c d
Levels: a < b < c < d

## 데이터 분류
- 수치형 : 숫자로 표현한다, 통계에서는 좀더 중요하다.
- 범주형 : 문자로 표한한다.

1) 수치형 - 이산형
- 셀 수 있으며 정수를 나타낸다.
- 값들이 서로 이어져 있지 않다.
- 예) 1명 2명 3명 등 서로 독립적이고 이어져 있지 않다.

2) 수치형 - 연속형
- 데이터가 연속적인 수치값이다. 주로 실수값이다.
- ex) 175.2cm, 180.12cm등 키를 나타내는 데이터는 연속형 데이터이다.
- 175~176 사이에는 많은수가 존재한다. 떼어낼 수 없는 독립적이지 않은 값이므로 연속형이라 한다.

3) 범주형 - 명목형
- 문자형태이다. 카테고리적 특징을 가진다.
- 카테고리를 정해 분류한다가 생각할 수 있다.
- 성별 카테고리, 종교 카테고리, 혈액형 카테고리 등 이안에 값이 담겨져 있다.
- 카테고리 level이라 부르며, level이 '남','여' 로 정해졌다면 데이터에 ['남','남','여'] '소녀'가 들어가면 안된다.
- level은 데이터 생성시 명시할 수 있다.
- ex) 성별(남,여) 종교(기독교,불교), 혈액형(A,B,AB,O)
- 때로는 남,여를 1,2의 숫자로 대신 사용해 통계분석을 하는 경우가 있다.

4) 범주형-순서형
- 명목형과 비슷하다. 단지 순서가 있다.
- ex) A+, A-, B+, B-, C+, C-, D+, D-, F

# PPT 자료문제

## LIST

In [237]:
# list()로 생성
x=list(1:5,c(T,F,T), "good day", matrix(1:6, ncol=2))
x

[[1]]
[1] 1 2 3 4 5

[[2]]
[1]  TRUE FALSE  TRUE

[[3]]
[1] "good day"

[[4]]
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

In [260]:
# list 요소 접근
x=list(1:5,c(T,F,T), "good day", matrix(1:6, ncol=2))
x[[1]] # 1성분요소 추출
x[[1]][2] # 1성분의 2요소 추출
x[1] # 리스트의 성분 서브리스트 추출
x[1:2] # 1,2 성분추출
x[[2]]
x[c(T,F,T)] #1,3 성분추출
x[1] = list(5:9) # 1성분 변경, list로 치환하여 변경
x
x[4:5] = list("happy", c(10,20,30)) # 4,5 성분에 리스트 추가
x

[1] 1 2 3 4 5

[1] 2

[[1]]
[1] 1 2 3 4 5

[[1]]
[1] 1 2 3 4 5

[[2]]
[1]  TRUE FALSE  TRUE

[1]  TRUE FALSE  TRUE

[[1]]
[1] 1 2 3 4 5

[[2]]
[1] "good day"

[[3]]
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

[[1]]
[1] 5 6 7 8 9

[[2]]
[1]  TRUE FALSE  TRUE

[[3]]
[1] "good day"

[[4]]
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

[[1]]
[1] 5 6 7 8 9

[[2]]
[1]  TRUE FALSE  TRUE

[[3]]
[1] "good day"

[[4]]
[1] "happy"

[[5]]
[1] 10 20 30

In [316]:
x = list(c(1,2,3,4,5), c(T,F,T), "good day", matrix(1:6, ncol=2))
y = list(name="hong", height=179, wight=77,score=c(100,30,80))
newlist = c(x,y)
m = unlist(newlist)

### DATAFRAME

In [315]:
# 데이터프레임 생성
d1 = data.frame(
    name=c("hong","kim","min"),
    height=c(178,166,174),
    weight=c(78.4,70.3,83.2),
    sex=c("male","male","female")
)
d1

name height weight sex   
1 hong 178    78.4   male  
2 kim  166    70.3   male  
3 min  174    83.2   female

In [320]:
# vector를 이용한 데이터프레임 생성
n=c("hong","min","kim") # 성명
h=c(172.6,155.7,180.9) # 키
a=c(20,50,19) # 나이
(d1 = data.frame(name=n,height=h,age=a))

name height age
1 hong 172.6  20 
2 min  155.7  50 
3 kim  180.9  19

In [329]:
# matrix를 이용한 데이터프레임 생성
# 같은 데이터형으로 구성된 번호, 키, 나이 행렬
dv = c(1,173,20,2,156,50,3,181,19)
# 행렬로 데이터 프레임 생성
m=matrix(dv, nrow=3, byrow=T)
d2=data.frame(m)

 # 열이름지정
cn = c("id","height","age")
names(m)=cn
d2

X1 X2  X3
1 1  173 20
2 2  156 50
3 3  181 19